name: 🔄 Switch Builds
on:
  workflow_call:

# Global Cache Settings
env:
  GODOT_BASE_BRANCH: 3.5
  SCONSFLAGS: verbose=yes warnings=all werror=no debug_symbols=no
  SCONS_CACHE_LIMIT: 4096

jobs:
  switch-template:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v3

      # Upload cache on completion and check it out now
      - name: Load .scons_cache directory
        id: switch-template-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.GODOT_BASE_BRANCH}}

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: switch
          target: release
          tools: false

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: bin/*
          retention-days: 14
