name: 🌱 PSVita Builds
on:
  workflow_call:

# Global Settings
env:
  GODOT_BASE_BRANCH: 3.5
  SCONSFLAGS: verbose=yes warnings=all werror=no debug_symbols=no

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-vita
  cancel-in-progress: true

jobs:
  vita-template:
    runs-on: "ubuntu-20.04"
    container: halotroop2288/vitasdk-ubuntu@main

    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: vita-template
        continue-on-error: true

      # Azure repositories are not reliable, we need to prevent Azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Setup PVR_PSP2
        run: |
          sudo apt-get install cmake libarchive-tools fakeroot zip -y
          git clone https://github.com/isage/vita-packages-extra
          cd vita-packages-extra/pvr_psp2
          vita-makepkg
          vdpm *-arm.tar.xz

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: vita
          target: release
          tools: false

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
