name: 🌱 PSVita Builds
on:
  workflow_call:

# Global Settings
env:
  GODOT_BASE_BRANCH: 3.5
  SCONSFLAGS: verbose=yes warnings=all werror=no debug_symbols=no

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-vita
  cancel-in-progress: true

jobs:
  vita-template:
    runs-on: ubuntu-latest

    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: vita-template
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Setup VitaSDK and PVR_PSP2
        run: |
          sudo apt-get install cmake libarchive-tools fakeroot zip -y
          git clone https://github.com/vitasdk/vdpm
          git clone https://github.com/isage/vita-packages-extra
          cd vdpm
          ./bootstrap-vitasdk.sh
          ./install-all.sh
          export PATH=$VITASDK/bin:$PATH
          vdpm vita-rss-libdl
          cd ../vita-packages-extra/pvr_psp2
          vita-makepkg
          vdpm *-arm.tar.xz

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: vita
          target: release
          tools: false

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
